This repo contains utilities that use Jenkins for early warnings/error detection in jiras and other jira tools.

== Contents of this repository 
- *README*: this file

- *render-testcase.py*: takes a report.json to render jira query results into junit.xml test reports

- **.json*: reports used by the Eclipse Che / Dev Spaces team for detecting stale/non-triaged/incorrect jiras

Steps to use it:

. Create a <reportname>.json file with the following format:

  [
  {
    "nofixversion": {
	"jql": "project = CRW AND fixVersion is EMPTY AND createdDate <= -7d",
        "description": "Issues have no fix version and was created 7 dags ago. Please triage."
    }
  },
  {
    "nocomponent": {
      "jql": "project in (CRW) AND component is EMPTY AND resolution is EMPTY",
      "description": "Issue has no component - please triage and make sure it is put in the right component or set of components."
    }
  }
  ]

+ 
Each entry has a report name used for identifying its results and then a jql for the query and finally a description which is added to each jira "error" message.
  
. Test it by running:

   ```
   $ python render-testcase.py -u user -p secret -s jiraserver -r <reportname>.json
   ```
+
Now for each report a -test.xml file will be created containing "test failures" for each jira matching the result.

. Setup a Jenkins build which executes the above script and enable junit reporting and you got automatic notification and tracking to help improve your jira content.


== Updating filters

To add a completely new filter requires a manual step since jira for some obscure reason does not support looking up filters by name.

When a new filter is added you have to do the following:

. Add it without an 'id' to the `.json` file
. Run the script, ie. `python setup_filters.py  -u jiralint -p secret -f filters.json,filters-composite.json`
. Commit the updated `.json` file which now will contain the newly created filter

Have fun! 
